# Choose an optional name for the datacenter
global:
  datacenter: gcp

# Enable the Consul Web UI via a NodePort
ui:
  service:
    type: 'LoadBalancer'

# Enable Connect for secure communication between nodes
connectInject:
  enabled: true

client:
  enabled: true
syncCatalog:
  enabled: true
# Use only one Consul server for local development
server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0

  extraConfig: |
    {
      "translate_wan_addrs": true
    }